apiVersion: v2
name: rivalapexmediation-console
description: RivalApexMediation Console Web Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ad-stack
  - console
  - frontend
maintainers:
  - name: RivalApexMediation Team
    email: dev@rivalapexmediation.com
