{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "console.fullname" . }}-{{ .Values.deployment.color }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "console.fullname" . }}-{{ .Values.deployment.color }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- $cpuOverrides := default (dict) .Values.autoscaling.targetCPUOverrides -}}
  {{- $cpuTarget := .Values.autoscaling.targetCPUUtilizationPercentage -}}
  {{- if hasKey $cpuOverrides .Values.deployment.color -}}
    {{- $cpuTarget = index $cpuOverrides .Values.deployment.color -}}
  {{- end -}}
  {{- if $cpuTarget }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $cpuTarget }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
