apiVersion: v2
name: rivalapexmediation-backend
description: RivalApexMediation Backend API Service
type: application
version: 1.1.0
appVersion: "1.0.0"
keywords:
  - ad-stack
  - backend
  - api
maintainers:
  - name: RivalApexMediation Team
    email: dev@rivalapexmediation.com
